[build]
  publish = "build"  # or "dist" or wherever your build output goes
  command = "npm run build"  # or the appropriate build command


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
